apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: local-l2-policy
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels: {} # all services
  nodeSelector:
    matchLabels: {} # all nodes
  interfaces:
    - ^eth[0-9]+$ # pi-cluster is only on wired networked
  externalIPs: true
  loadBalancerIPs: true
