apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "tailscale"
        matchRule: Host(`instance-2.marlin-daggertooth.ts.net`)
        entryPoints: ["websecure"]
        tls:
          certResolver: myresolver
    logs:
      access:
        enabled: true
        format: json
    certificatesResolvers:
      myresolver:
        acme:
          email: thecodeviking@gmail.com
          storage: /data/acme.json
          tlsChallenge: true
          caServer: "https://acme-v02.api.letsencrypt.org/directory"
        tailscale: {}
