apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.acmeresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.acmeresolver.acme.dnschallenge.provider=namedotcom"
      - "--certificatesresolvers.acmeresolver.acme.email=thecodeviking@gmail.com"
      - "--certificatesresolvers.acmeresolver.acme.storage=/data/acme.json"
      - "--api"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: ["traefik"]
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    env:
      - name: NAMEDOTCOM_USERNAME
        valueFrom:
          secretKeyRef:
            name: namedotcom-api
            key: username
      - name: NAMEDOTCOM_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: namedotcom-api
            key: token
    persistence:
      enabled: true
      path: /data
  valuesSecrets:
    - name: traefik-tailscale-config
      ignoreUpdates: false
      keys:
        - configValues
